### ISSUE TITLE
question: other neural interpreters?

### ISSUE THREAD

**Issue by monperrus** [mokemokechicken/keras_npi#5]
I've just run keras_npi successfully. Congrats and thanks a lot for putting such as usable and documented piece of code on Github.

Have you seen other neural interpreters somewhere on Github or on the web?

**Comment by mokemokechicken** [comment]
Hi, @monperrus 
Thank you for your comment.

> Have you seen other neural interpreters somewhere on Github or on the web?

I have not seen it. (I have not searched much...)

**Comment by monperrus** [comment]
Thanks
